import { describe, expect, it } from 'vitest';
import { readdir, readFile } from 'node:fs/promises';
import { join } from 'node:path';

const sourceFiles = async (directory: string): Promise<string[]> => {
  const entries = await readdir(directory, { withFileTypes: true });
  const nestedFiles = await Promise.all(
    entries.map(async (entry) => {
      const path = join(directory, entry.name);
      return entry.isDirectory() ? sourceFiles(path) : [path];
    }),
  );
  return nestedFiles.flat();
};

describe('Archive integrity layout', () => {
  it('keeps em dashes out of Web copy', async () => {
    const allFiles = await sourceFiles('src');
    const files = allFiles.filter((file) => file.endsWith('.svelte') || file.endsWith('.ts'));
    const sources = await Promise.all(files.map(async (file) => ({ file, source: await readFile(file, 'utf8') })));
    const violations = sources.filter(({ source }) => source.includes('\u2014')).map(({ file }) => file);

    expect(violations).toEqual([]);
  });

  it('keeps exact duplicate discovery explicit, inspectable and read-only', async () => {
    const pageSource = await readFile('src/routes/(user)/cimmich/archive-integrity/+page.svelte', 'utf8');
    const exactResults = await readFile('src/lib/components/cimmich/ArchiveExactDuplicateResults.svelte', 'utf8');
    const variantResults = await readFile('src/lib/components/cimmich/ArchiveVariantResults.svelte', 'utf8');
    const source = [pageSource, exactResults, variantResults].join('\n');
    const pageLoad = await readFile('src/routes/(user)/cimmich/archive-integrity/+page.ts', 'utf8');
    const backupProof = await readFile('src/lib/components/cimmich/ArchiveBackupProof.svelte', 'utf8');
    const folderComparison = await readFile('src/lib/components/cimmich/ArchiveFolderComparison.svelte', 'utf8');
    const rotationReview = await readFile('src/lib/components/cimmich/ArchiveRotationReview.svelte', 'utf8');
    const variants = await readFile('src/lib/components/cimmich/archive-variant-groups.ts', 'utf8');
    const maintenance = await readFile('src/routes/(user)/cimmich/maintenance/+page.svelte', 'utf8');
    const folderPage = await readFile(
      'src/routes/(user)/folders/[[photos=photos]]/[[assetId=id]]/+page.svelte',
      'utf8',
    );
    const normalizedSource = source.replaceAll(/\s+/g, ' ');

    expect(pageLoad).toContain("title: 'Archive Health'");
    expect(source).toContain('{#snippet buttons()}');
    expect(source).not.toContain('<h1');
    expect(source).toContain('Exact means byte-for-byte');
    expect(source).toContain('Route.viewAsset({ id: copy.sourceAssetId })');
    expect(source).toContain('Source folder');
    expect(source).toContain('getParentPath(originalPath)');
    expect(source).toContain('Route.viewFolderAsset({ cimmich: 1, id: copy.sourceAssetId, path: folderPath })');
    expect(source).toContain("Route.cimmichArchiveIntegrity({ folder: folderPath, mode: 'folder' })");
    expect(source).toContain('loadExactPaths(page.groups)');
    expect(source).toContain('Math.min(6, pending.length)');
    expect(source).toContain('Possible duplicates');
    expect(normalizedSource).toContain('A visual match is a review lead, not deletion proof');
    expect(variants).toContain('Immich People differ');
    expect(normalizedSource).toContain('Cimmich intelligence follows verified content');
    expect(source).not.toContain('resolveDuplicates');
    expect(source).not.toContain('suggestedKeepAssetIds');
    expect(source).not.toContain('Canonical plan');
    expect(source).toContain('Recommended to keep');
    expect(source).toContain('No safe recommendation');
    expect(source).toContain('Why this recommendation');
    expect(source).toContain('archiveVariantFolderContext(contextGroups, asset)');
    expect(source).toContain('title={data.meta.title}');
    expect(source).not.toContain('Back to Archive Health');
    expect(source).toContain('Open this folder in Library');
    expect(source).toContain('Refresh only the selected check');
    expect(source).toContain('Folder check');
    expect(source).toContain('Compare one folder with the rest of the archive');
    expect(source).toContain('Most impacted folders');
    expect(source).toContain('rankArchiveFoldersByImpact(nativeVariantGroups)');
    expect(source).toContain('affectedAssetCount');
    expect(source).toContain('counterpartFolderCount');
    expect(source).toContain("'affected file'");
    expect(source).toContain("'other folder'");
    expect(source).toContain('name="folder"');
    expect(source).toContain('onsubmit={submitFolder}');
    expect(source).toContain("goto(Route.cimmichArchiveIntegrity({ folder: folderPath, mode: 'folder' })");
    expect(source).toContain('replaceState: true');
    expect(source).toContain('archiveVariantGroupsInFolder(allNativeGroups, folderPath)');
    expect(source).toContain('readArchiveEvidence(sourceAssetIds)');
    expect(source).toContain('uniqueSourceAssetIds.slice(index * 20, index * 20 + 20)');
    expect(source).toContain('nativeGroups.slice(0, 12)');
    expect(source).toContain('loadMoreVariants');
    expect(source).toContain('Comparisons load as needed');
    expect(source).toContain('This comparison took too long');
    expect(source).toContain("case 'exact':");
    expect(source).toContain("case 'folder':");
    expect(source).not.toContain('void loadFolderAssets();');
    expect(source).toContain("folder: folderContext.path, mode: 'folder'");
    expect(folderPage).toContain('Check this folder');
    expect(folderPage).toContain("mode: 'folder'");
    expect(source.match(/data-sveltekit-reload/g)?.length ?? 0).toBeLessThanOrEqual(2);
    expect(source).toContain('other flagged photo');
    expect(source).toContain('Technical details');
    expect(variants).toContain("status: 'hold_ambiguous'");
    expect(variants).toContain('originalCaptureExtensions');
    expect(source).toContain('Backup check');
    expect(source).toContain('Rotation review');
    expect(source).toContain("case 'rotation':");
    expect(source).toContain('searchSmart({');
    expect(source).toContain('query: ROTATION_VISUAL_QUERY');
    expect(source).toContain('type: AssetTypeEnum.Image');
    expect(source).toContain('getCimmichArchiveSourceEvidence(nextAssets.map((asset) => asset.id))');
    expect(source).toContain('getCimmichAssetCorrections(sourceEvidence.items.map((item) => item.assetId))');
    expect(source).toContain('ROTATION_PAGE_SIZE = 24');
    expect(source).toContain('rotationNextPage = Number(next.assets.nextPage) || 0');
    expect(source).toContain('<ArchiveRotationReview');
    expect(rotationReview).toContain('Likely rotation candidates');
    expect(rotationReview).toContain("Immich's visual index ranks");
    expect(rotationReview).toContain('Why flagged');
    expect(rotationReview).toContain('EXIF orientation');
    expect(rotationReview).toContain('Reversible Cimmich correction');
    expect(rotationReview).toContain('Source folder unavailable');
    expect(rotationReview).toContain('<CimmichReviewPhotoMedia');
    expect(rotationReview).toContain('targetLabel="Review orientation"');
    expect(rotationReview).toContain("rotateDraft(item, 'left')");
    expect(rotationReview).toContain("rotateDraft(item, 'right')");
    expect(rotationReview).toContain("dirty ? 'Save' : confirmed ? 'Confirmed' : 'Confirm'");
    expect(rotationReview).toContain('Save / Confirm all (${pendingItems.length})');
    expect(rotationReview).toContain('pendingItems.map');
    expect(rotationReview).toContain('currently shown on this page');
    expect(source).toContain('changes.slice(index, index + 100)');
    expect(rotationReview).toContain('onUndo(item)');
    expect(rotationReview).toContain('Source files and Immich metadata are unchanged');
    expect(folderComparison).toContain('Biggest overlaps');
    expect(folderComparison).toContain('Show top 6 only');
    expect(folderComparison).toContain('Also found elsewhere');
    expect(folderComparison).toContain('No match elsewhere');
    expect(folderComparison).toContain('Repeated only inside');
    expect(folderComparison).toContain('Check byte details');
    expect(folderComparison).toContain('Every copy is on one line. Highlighted rows contain different values.');
    expect(folderComparison).toContain('alignAssets(group.here, outsideAssets)');
    expect(folderComparison).toContain('repeat(${comparisonAssets.length}, 13rem)');
    expect(folderComparison).toContain('group block aspect-4/3 w-full');
    expect(folderComparison).toContain('Recommended to keep');
    expect(folderComparison).toContain('Review only');
    expect(folderComparison).toContain('This is a review recommendation, not deletion proof.');
    expect(folderComparison).toContain("plan.status === 'hold_exact' || plan.status === 'hold_ambiguous'");
    expect(folderComparison).toContain('visibleRecommendation(group.canonicalPlan, comparisonAssets)');
    expect(folderComparison).toContain('The archive-wide winner is outside this folder pair.');
    expect(folderComparison).toContain('No safe recommendation');
    expect(folderComparison).toContain('recommendedAssetId === asset.id');
    expect(folderComparison).toContain("label: 'File location'");
    expect(folderComparison).toContain("label: 'File size'");
    expect(folderComparison).toContain("label: 'Resolution'");
    expect(folderComparison).toContain("label: 'Captured'");
    expect(folderComparison).toContain("label: 'File modified'");
    expect(folderComparison).toContain("label: 'Photo location'");
    expect(folderComparison).toContain("label: 'Camera'");
    expect(folderComparison).toContain('More Immich metadata, same columns');
    expect(folderComparison).toContain("label: 'Rotation'");
    expect(folderComparison).toContain("label: 'Description'");
    expect(folderComparison).toContain("label: 'Rating'");
    expect(folderComparison).toContain("label: 'Immich People'");
    expect(folderComparison).toContain("label: 'Immich Tags'");
    expect(folderComparison).toContain("label: 'Favourite'");
    expect(folderComparison).toContain("label: 'Archive status'");
    expect(folderComparison).toContain("label: 'Visibility'");
    expect(backupProof).toContain('Retirement safety gate');
    expect(backupProof).toContain('No independent backup connected');
    expect(backupProof).toContain('targetsLoaded && targets.length > 0');
    expect(backupProof).toContain('Independent backup proof');
    expect(backupProof).toContain('0 verified independent destinations');
    expect(backupProof).toContain('distinct failure domain');
    expect(backupProof).toContain('Future retirement also requires the owner-approved sidecar set');
    expect(backupProof).toContain('Not proven');
    expect(backupProof).not.toContain("method: 'POST'");
    expect(source).not.toContain('Next integrity layers');
    expect(source).not.toContain('Sidecar export');
    expect(source).not.toContain("method: 'POST'");
    expect(maintenance).toContain('Route.cimmichArchiveIntegrity()');
    expect(maintenance).toContain('Exact duplicate discovery');
  });
});
