export type CimmichIdentityAuditRun = {
  acceptedComparableFaces: number;
  acceptedEmbeddedFaces: number;
  auditRunId: string;
  completedAt: string | null;
  contradictionCandidates: number;
  contradictionQueriesEligible: number;
  derivativeCandidatesSuppressed: number;
  errorCode: string | null;
  independenceCandidatesEligible: number;
  independenceCandidatesVerified: number;
  independenceComparisonLimit: number | null;
  independenceProviderConfigDigest: string | null;
  independenceScoreFloor: number;
  independenceVerificationTruncated: boolean;
  marginFloor: number;
  packId: string;
  policyVersion: string;
  queryFrontierLimit: number;
  queryFrontierTruncated: boolean;
  schemaVersion: 'cimmich.identity-audit.v2';
  scoreFloor: number;
  stale: boolean;
  startedAt: string;
  state: 'completed' | 'failed' | 'running';
  truncationProjectionComplete: boolean;
  untaggedCandidates: number;
  untaggedEmbeddedFaces: number;
  untaggedQueriesEligible: number;
};
