export type CimmichIdentityCandidate = {
  asset_id: string;
  box_h: number;
  box_w: number;
  box_x: number;
  box_y: number;
  calibrated_confidence: number | null;
  capture_time: string | null;
  cluster_id?: string | null;
  current_claim_id?: string | null;
  current_decision_id: string | null;
  current_person_id?: string | null;
  current_person_name?: string | null;
  current_revision: number;
  detection_confidence: number;
  display_name: string;
  face_id: string;
  filename: string;
  height: number;
  identity_claim_id: string;
  media_kind: 'image' | 'video';
  match_score?: number | null;
  origin?: 'cluster_propagation' | 'prime_match' | string;
  person_id: string;
  quality_measurements: Record<string, number | string>;
  same_photo_accepted_count?: number;
  sourceAssetId: string;
  source_margin: number | null;
  source_score: number | null;
  width: number;
};
